CREATE TABLE `hs_app_order` (
  `id` varchar(64) NOT NULL,
  `ckAppId` varchar(16) DEFAULT NULL COMMENT 'ckapp的id',
  `ckChannelId` varchar(16) DEFAULT NULL COMMENT 'ck渠道id',
  `channelId` varchar(32) DEFAULT NULL COMMENT 'hs渠道id',
  `mmAppId` varchar(32) DEFAULT NULL COMMENT 'mm应用id',
  `imei` varchar(300) DEFAULT NULL COMMENT '国际移动设备标识',
  `imsi` varchar(32) DEFAULT NULL COMMENT '国际移动用户识别码',
  `appId` varchar(32) NOT NULL COMMENT '应用ID',
  `qn` varchar(32) NOT NULL COMMENT '渠道ID',
  `fee` int(7) NOT NULL COMMENT '成功金额',
  `paystatus` tinyint(1) NOT NULL COMMENT '付费状态(1:成功，其它:失败)',
  `hsOrderId` varchar(32) NOT NULL COMMENT 'hs订单id',
  `OrderId` varchar(32) NOT NULL COMMENT 'ck订单号',
  `payCount` int(2) DEFAULT NULL COMMENT '支付的次数',
  `ackType` int(1) DEFAULT NULL COMMENT '支付确认的类型',
  `isOnline` tinyint(1) DEFAULT NULL COMMENT '是否是网游',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `update_date` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `index_orderId` (`OrderId`),
  KEY `index_channelId` (`ckChannelId`),
  KEY `index_ckAppId` (`ckAppId`),
  KEY `index_imsi` (`imsi`),
  KEY `index_createTime` (`create_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8