CREATE TABLE `app_offline_pay` (
  `id` varchar(255) NOT NULL COMMENT '表ID',
  `ckChannelId` varchar(64) DEFAULT NULL COMMENT '渠道号',
  `ckAppId` varchar(64) DEFAULT NULL COMMENT '游戏编号',
  `mmAppId` varbinary(255) DEFAULT NULL COMMENT 'mmAppid',
  `imsi` varchar(32) DEFAULT NULL COMMENT '移动用户的唯一号',
  `imei` varchar(20) DEFAULT NULL COMMENT '移动设备卡的唯一号',
  `iccid` varchar(32) DEFAULT NULL COMMENT 'IC卡的唯一识别号码',
  `androidId` varchar(256) DEFAULT NULL COMMENT 'androidId',
  `versionName` varchar(64) DEFAULT NULL COMMENT '版本号',
  `payType` varchar(64) DEFAULT NULL COMMENT '支付方式',
  `errMsg` varchar(255) DEFAULT NULL,
  `prices` varchar(64) DEFAULT NULL COMMENT '价格',
  `appPayContent` text COMMENT '客户端的支付信息',
  `times` int(4) DEFAULT NULL COMMENT '时间段内的统计次数',
  `period` int(4) DEFAULT NULL COMMENT '时间段,单位:天',
  `status` int(4) DEFAULT NULL COMMENT '0:成功,1:超限,2:参数缺失,3未配置,4失败',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `index_ckAppId` (`ckAppId`),
  KEY `index_ckChannelId` (`ckChannelId`),
  KEY `index_payType` (`payType`),
  KEY `index_imsi` (`imsi`),
  KEY `index_iccid` (`iccid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
